<a href="https://colab.research.google.com/github/hooper625/College/blob/main/Activity7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import pandas as pd

#Create a numpy array of the shape (3,5) with random values from 1 to 100
array = np.random.randint(1, 100, (3, 5))
print(f"The array is:")
print(array)
#generate a Data Frame with index = a,b,c and columns 1.2,3,4,5.
df = pd.DataFrame(array, index=['a', 'b', 'c'], columns=[1, 2, 3, 4, 5])
print(f"The Data Frame is:")
print(df)
#Transpose the DataFrame
print(f"The Data Frame transposed is:")
transposed = df.T
print(transposed)
#Changed the values less than 40 to 0 in the Data Frame
transposed[transposed < 40] = 0
print(f"The Data Frame with values less than 40 set to 0 is:")
print(transposed)

The array is:
[[19 57  3 97 30]
 [12 24 25 82 20]
 [61 61 66 54 41]]
The Data Frame is:
    1   2   3   4   5
a  19  57   3  97  30
b  12  24  25  82  20
c  61  61  66  54  41
The Data Frame transposed is:
    a   b   c
1  19  12  61
2  57  24  61
3   3  25  66
4  97  82  54
5  30  20  41
The Data Frame with values less than 40 set to 0 is:
    a   b   c
1   0   0  61
2  57   0  61
3   0   0  66
4  97  82  54
5   0   0  41
